services:
    qgis-server: #map server
        image: camptocamp/qgis-server
        volumes:
            - ./qgis:/etc/qgisserver:ro
        environment:
            - LANG=en_EN.UTF-8
            - QGIS_PROJECT_FILE=/etc/qgisserver/project.qgz
            - QGIS_SERVER_LANDING_PAGE_PROJECTS_DIRECTORIES=/etc/qgisserver/
            #- QGIS_SERVER_LOG_LEVEL=0  # INFO (log all requests)
            #- DEBUG=1                  # display env before spawning QGIS Server
        ports:
            - 80:80


    postgis: #Spatial database
        restart: always
        ports:
            - '5432:5432'
        user: root
        # POSTGIS VOLUME IS NOT CONFIGURED BECAUSE DATA FOLDER CANNOT BE INSIDE THE SRC FOLDER
        volumes:
            - './data/postgres:/var/lib/postgresql/data'
            #- './logs/postgres:/var/log/postgresql/'
            #- './configs/create_databases.sh:/docker-entrypoint-initdb.d/create_databases.sh'
        logging:
            options:
                max-size: 1g
        environment:
            POSTGRES_PASSWORD: test
            POSTGRES_USER: postgres
            POSTGRES_DB: geodataimporter
            PGDATESTYLE: "ISO, DMY"
            PGDATA: /var/lib/postgresql/data
        image: postgis/postgis
        command: ["postgres"] #, "-c", "logging_collector=on", "-c", "log_statement=none", "-c", "log_directory=/var/log/postgresql/"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            retries: 5
            start_period: 10s
        hostname: postgis

    geodataimporter:
        build: .
        volumes:
            - '.:/usr/src/app'
        ports:
            - '8000:8000'
        environment:
            DB_PASSWORD: test
            DB_USER: postgres
            DB_NAME: geodataimporter
            DB_HOST: postgis
            DB_PORT: 5432
        depends_on:
            postgis:
                condition: service_healthy
        restart: always
