# Generated by Django 5.1.7 on 2025-07-06 02:32

import django.contrib.gis.db.models.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Importar_Arquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('arquivo', models.FileField(upload_to='uploads/')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='product_index',
            fields=[
                ('area', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('metadataid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('scale', models.IntegerField()),
                ('file_path', models.FilePathField(path='.')),
            ],
        ),
    ]
